### ISSUE TITLE
Workflow extension  - Entity Property Set Action for Step type

### ISSUE THREAD

**Issue by Senaloraine** [BEMADEV/Room-Management#25]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

This action when set to Entity Property Set, and we look to set the step status by id, it updates the value in all workflows that use this action and property set, though each workflow is intended to update a unique step.
Here is a video demo of the bug in action: 
[Video Demo](https://soapbox.wistia.com/videos/zA2PlkeucE)

### Expected Behavior

Expected Behavior 

### Actual Behavior

Actual Behavior see video above 

### Steps to Reproduce

- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error
See video above

### Rock Version

15.1 in Prod/ 15.2 in Dev Issue is in both

### Plugin Version

Don't show a version, but it says installed and it was last updated 9/22/2023

### Client Culture Setting

en-US

**Comment by tcavaletto** [comment]
Hi @Senaloraine ! This is a core bug with Matrixes, which is that they are stored in their own table, with their Attribute Value only being a link to their Guid, Because of this, when you copy a workflow with a matrix in it, like Workflow A pointing to Matrix A's guid, the new workflow, Workflow B, _also_ has an attribute value pointing to Matrix A's guid, so a change in one changes the other.

The best way to resolve this is to delete the action with the matrix in it, and rebuild it so that it points to a new 'Matrix B'.
