### ISSUE TITLE
Calendar support for linking to apps such as Google Calendar from URL

### ISSUE THREAD

**Issue by tcavaletto** [BEMADEV/Room-Management#3]
Before submitting an enhancement request, please check the existing issues to see if the feature you want has already been requested. If so, please add a comment or thumbs up so that we can see the level of community interest in it!

**Comment by bscottdavis** [comment]
Hi @tcavaletto! Thanks for your work on this! I stumbled across the /Webhooks/GetReservationCalendarFeed.ashx endpoint that appears to work fairly well, except that reservations do not appear to update in the calendar even long after the update on the Rock side is made. (A couple weeks have gone by and the event still shows the original information, rather than what was updated a couple of weeks ago.)

It appears that the endpoint is not included in the documentation. Is it something that is ready for use or is it still under development?
