### ISSUE TITLE
Rock Tree Loading Slowly for Parent Locations

### ISSUE THREAD

**Issue by Vuvvy1** [BEMADEV/Room-Management#41]
![image](https://github.com/BEMADEV/Room-Management/assets/101690891/639c427c-2238-421f-ad3d-e72943fe6efb)

The Rock tree is loading slowly for every parent location selected. Even if there is only one child location, it still takes a long time to load the location and for the status to change to red or green. Multiple churches have confirmed experiencing the same slow load times.

Request:
Ideally, this would be optimized and/or have a faster method for selecting rooms.

**Comment by Vuvvy1** [comment]
Hi @tcavaletto,

Thank you for addressing this issue! Could you share if any specific changes were made to improve the loading speed of the Rock tree? Just wondering if there’s anything I should check or verify on my end.

Thanks!

**Comment by tcavaletto** [comment]
Yep! There are two main changes. First, we now only check against present and future occurrences. Second, instead of grabbing everything a year out, we only grab reservations between the first occurrence start date and last occurrence end date. This should increase performance across the board, but especially for one-time reservations.

**Comment by Vuvvy1** [comment]
> Yep! There are two main changes. First, we now only check against present and future occurrences. Second, instead of grabbing everything a year out, we only grab reservations between the first occurrence start date and last occurrence end date. This should increase performance across the board, but especially for one-time reservations.

Great to hear!
